### ISSUE TITLE
Add logos from companies

### ISSUE THREAD

**Issue by JonasTriki** [echo-uib/echo-karriere#10]
Vi mangler en god del logoer fra bedrifter (kommer inn fortløpende på mail)

**Comment by sondr3** [comment]
- [ ] Bekk
- [ ] Cognite
- [ ] Equinor
- [ ] Kantega
- [ ] Miles
- [ ] NetCompany
- [ ] Accenture
- [ ] Computas
- [ ] Gjensidige
- [ ] NAV
- [ ] Simula
- [ ] Skatteetaten
- [ ] Sparebanken vest
- [ ] NetSecurity
- [ ] Difi
- [ ] Hatteland
- [ ] Knowit
- [ ] Capgemini
- [ ] Visma
- [ ] Tripletex
- [ ] Sbanken
- [ ] Sopra Steria
- [ ] IslandGarden
- [ ] Stacc
- [ ] TV2
- [ ] Netlight
- [ ] Infodoc
- [ ] Digitroll
- [ ] Insituttet
